# POCKET VARIABLES
POCKET_URL = "https://getpocket.com/v3"
POCKET_CONSUMER_KEY = "CHANGE-ME"
REDIRECT_URI = "about:blank"

## WALLABAG VARIABLES
WALLABAG_URL = "https://CHANGE.ME"
WALLABAG_CLIENT_ID = "CHANGE_ME"
WALLABAG_CLIENT_SECRET = "CHANGE_ME"
WALLABAG_USERNAME = "CHANGEME"
WALLABAG_PASSWORD = "CHANGE_ME"